export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';

export const GET_USUARIOS = 'GET_USUARIOS';
export const GET_USUARIO = 'GET_USUARIO';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';

export const GET_TORNEOS = 'GET_TORNEOS';
export const GET_TORNEO = 'GET_TORNEO';
export const REGISTRO_TORNEO_EXITOSO = 'REGISTRO_TORNEO_EXITOSO';
export const REGISTRO_TORNEO_ERROR = 'REGISTRO_TORNEO_ERROR';
export const EDITAR_TORNEO = 'EDITAR_TORNEO';
export const BORRAR_TORNEO = 'BORRAR_TORNEO';

export const GET_EQUIPOS = 'GET_EQUIPOS';
export const GET_EQUIPO = 'GET_EQUIPO';
export const REGISTRO_EQUIPO_EXITOSO = 'REGISTRO_EQUIPO_EXITOSO';
export const REGISTRO_EQUIPO_ERROR = 'REGISTRO_EQUIPO_ERROR';
export const EDITAR_EQUIPO = 'EDITAR_EQUIPO';
export const BORRAR_EQUIPO = 'BORRAR_EQUIPO';

export const GET_ORGANIZACIONES = 'GET_ORGANIZACIONES';
export const GET_ORGANIZACION = 'GET_ORGANIZACION';
export const REGISTRO_ORGANIZACION_EXITOSO = 'REGISTRO_ORGANIZACION_EXITOSO';
export const REGISTRO_ORGANIZACION_ERROR = 'REGISTRO_ORGANIZACION_ERROR';
export const EDITAR_ORGANIZACION = 'EDITAR_ORGANIZACION';
export const BORRAR_ORGANIZACION = 'BORRAR_ORGANIZACION';

export const GET_INSCRIPCIONES = 'GET_INSCRIPCIONES';
export const GET_INSCRIPCION = 'GET_INSCRIPCION';
export const REGISTRO_INSCRIPCION_EXITOSO = 'REGISTRO_INSCRIPCION_EXITOSO';
export const REGISTRO_INSCRIPCION_ERROR = 'REGISTRO_INSCRIPCION_ERROR';
export const EDITAR_INSCRIPCION = 'EDITAR_INSCRIPCION';
export const BORRAR_INSCRIPCION = 'BORRAR_INSCRIPCION';

export const GET_ENCUENTROS = 'GET_ENCUENTROS';
export const GET_ENCUENTRO = 'GET_ENCUENTRO';
export const REGISTRO_ENCUENTRO_EXITOSO = 'REGISTRO_ENCUENTRO_EXITOSO';
export const REGISTRO_ENCUENTRO_ERROR = 'REGISTRO_ENCUENTRO_ERROR';
export const EDITAR_ENCUENTRO = 'EDITAR_ENCUENTRO';
export const BORRAR_ENCUENTRO = 'BORRAR_ENCUENTRO';
